name: lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  flake-check:
    name: "Check Flake formatting and linting: ${{ matrix.library }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        library: [jump_babel, jump_portrait, jump_rr, trommel]
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Check Formatting
        run: |
          cd ./libs/${{ matrix.library }}
          nix fmt 
          git diff --exit-code
      - name: Run Flake Check
      
        run: |
          cd ./libs/${{ matrix.library }}
          nix flake check ./libs/${{ matrix.library }}
